### ISSUE TITLE
HTML files have an awful dark background compared to other files?

### ISSUE THREAD

**Issue by Cyan101** [siannopollo/ruby-blue-atom#1]
![HTML](https://cdn.discordapp.com/attachments/225375815087554563/337784370578587651/Screenshot_2017-07-21_at_10.34.04_AM.png)
![Non-HTML](https://cdn.discordapp.com/attachments/225375815087554563/337784367147384842/Screenshot_2017-07-21_at_10.34.12_AM.png)

I love this theme in my CSS/Crystal and Ruby stuff, but when editing HTML files the syntax highlighting colours and the background just feel too different and not like the rest of this theme.

**Comment by siannopollo** [comment]
I wouldn't say it's awful :-)

But the reason why those files are different is because it was that way in the original TextMate theme that this was based off of. That, and I personally like to have a distinction between text-ish files and ruby files (maybe that's because I used the TextMate theme for so long).

You can override that styling in your personal stylesheet if you like. Here are the selectors to override:

```css
atom-text-editor, atom-text-editor.editor {
  &[data-grammar="text html basic"],
  &[data-grammar="text html erb"],
  &[data-grammar="text haml"],
  &[data-grammar="text xml"],
  &[data-grammar="source gfm"],
  &[data-grammar="text gherkin feature"] {
    background-color: #21374F;
  }
}
```
